name: Release Linux

on:
  workflow_dispatch:

# Declare default permissions as readonly.
permissions: read-all

env:
  APP_NAME: ${{ secrets.APP_NAME }}

jobs:
  release:
    name: Package ${{ matrix.platform }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: Linux
            runs-on: ubuntu-24.04
            build-script: ./scripts/package/linux.sh

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ secrets.GIT_REPO }}
          ref: main
          token: ${{ secrets.GIT_PAT }}

      - name: Setup Java
        if: matrix.platform == 'Android'
        uses: actions/setup-java@v4
        with:
          java-version: "17.x"
          distribution: "temurin"

      - name: Switch xcode 16.3
        if: matrix.platform == 'iOS'
        run: sudo xcode-select --switch /Applications/Xcode_16.3.app

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.32.5"

      - name: Build ${{ matrix.platform }}
        if: matrix.platform != 'Windows'
        run: ${{ matrix.build-script }}
        env:
          AGE_PRIVATE_KEY: ${{ secrets.AGE_PRIVATE_KEY }}
        shell: bash

      - name: Build ${{ matrix.platform }}
        if: matrix.platform == 'Windows'
        run: ${{ matrix.build-script }}
        env:
          AGE_PRIVATE_KEY: ${{ secrets.AGE_PRIVATE_KEY }}
        shell: pwsh

      - name: Get version from pubspec.yaml
        id: version
        run: |
          VERSION=$(grep "version:" pubspec.yaml | head -1 | sed 's/version: //' | sed 's/+.*$//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        shell: bash

      - name: Upload to R2
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: artifacts
          output-file-url: false
          destination-dir: ${{ secrets.APP_NAME }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: matrix.platform != 'iOS'
        with:
          tag_name: "v${{ steps.version.outputs.version }}"
          name: "Release v${{ steps.version.outputs.version }}"
          files: |
            artifacts/latest/*.apk
            artifacts/latest/*.exe
            artifacts/latest/*.zip
            artifacts/latest/*.dmg
            artifacts/latest/*.deb
            artifacts/latest/*.rpm
            artifacts/latest/*.appimage
          body_path: documents/changelog.md
          repository: ${{ secrets.RELEASE_REPO }}
          token: ${{ secrets.GIT_PAT }}
          draft: false
          prerelease: false

  appcast:
    name: Upload Appcast to R2
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ secrets.GIT_REPO }}
          ref: main
          token: ${{ secrets.GIT_PAT }}

      - name: Generate Appcast
        run: |
          mkdir -p artifacts/latest
          cp documents/appcast/windows*.xml artifacts/latest/
          cp documents/appcast/android*.xml artifacts/latest/
          cp documents/appcast/linux*.xml artifacts/latest/
          cp documents/appcast/ios*.xml artifacts/latest/

      - name: Upload to R2
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: artifacts
          output-file-url: false
          destination-dir: ${{ secrets.APP_NAME }}
