name: Release iOS TestFlight

on:
  workflow_dispatch:

permissions: read-all

env:
  APP_NAME: ${{ secrets.APP_NAME }}

jobs:
  release:
    name: Release iOS TestFlight
    runs-on: macos-26

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ secrets.GIT_REPO }}
          ref: main
          token: ${{ secrets.GIT_PAT }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.41.6"

      - name: Build iOS and Upload to TestFlight
        run: bash scripts/package/ios.sh --tf-only
        env:
          AGE_PRIVATE_KEY: ${{ secrets.AGE_PRIVATE_KEY }}
        shell: bash
